name: saba2v2
description: "تطبيق سبأ لتقديم خدمات مخصصة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 15.0.0
  file_picker: 10.1.7
  provider: 6.1.2
  shared_preferences: 2.3.0
  intl: 0.20.2
  permission_handler: 11.3.1
  url_launcher: 6.1.10
  flutter_native_splash: 2.4.6
  http: 1.4.0
  dio: ^5.4.0
  mime: 1.0.4
  cached_network_image: 3.3.1
  flutter_svg: 2.0.10
  fl_chart: 0.63.0
  dropdown_button2: 2.3.9
  image_picker: 1.1.2
  timeago: 3.7.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.13.1   # (أحدث إصدار وقت كتابة الرسالة)

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# ✅ هنا القسم لازم يكون خارج قسم flutter
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"